# Generated by Django 2.0.7 on 2018-08-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0006_brand_image'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='ce867a33-fddf-4e60-89ec-179c9792889d', on_delete=django.db.models.deletion.CASCADE, to='locator.Category'),
            preserve_default=False,
        ),
    ]
