# Generated by Django 2.1 on 2018-08-08 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), default='{}', max_length=2805, size=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sender',
            field=models.CharField(default='shoppstar', max_length=255),
        ),
    ]
