# Generated by Django 2.1 on 2018-08-08 20:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180808_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='external_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=255, null=True), max_length=2805, size=10),
        ),
    ]
