# Generated by Django 2.1 on 2018-08-09 18:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180808_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=255, null=True), blank=True, max_length=2805, null=True, size=10),
        ),
    ]
