# Generated by Django 2.1 on 2018-08-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180809_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
