# Generated by Django 2.1 on 2018-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_top',
            field=models.NullBooleanField(default=False),
        ),
    ]
