# Generated by Django 2.0.7 on 2018-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='storeUrl',
            new_name='store_url',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.NullBooleanField(default=False),
        ),
    ]
