# Generated by Django 2.0.6 on 2018-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_auto_20180701_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(default=' '),
        ),
    ]
