# Generated by Django 2.0.7 on 2018-08-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0005_auto_20180804_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
