# Generated by Django 2.0.6 on 2018-07-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0005_auto_20180704_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
