# Generated by Django 2.1 on 2018-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0008_category_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
